# Generated by Django 6.0.7 on 2026-07-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('issue', models.CharField(choices=[('Invoice Request', 'Invoice Request'), ('Insurance Claim', 'Insurance Claim'), ('Payment Issue', 'Payment Issue'), ('Refund', 'Refund'), ('Other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
